name: LEDAcrypt
type: kem
claimed-nist-level: <N>
claimed-security: IND-CPA/IND-CCA2  # KEM only
length-public-key: <N>          # KEM and signature
length-secret-key: <N>          # KEM and signature
length-ciphertext: <N>          # KEM only
length-shared-secret: <N>       # KEM only
length-signature: <N>           # Signature only
nistkat-sha256: sha256sum of 1st NIST KAT test case # KEM and signature
testvectors-sha256: sha256sum of output of testvectors # Signature only
principal-submitters:
  - Alice
  - Bob
  - ...
auxiliary-submitters: # optional
  - Alice
  - Bob
  - ...
implementations:
  - name: clean
    version: <some version indicator>